const fs=require('fs'),path=require('path');
const run=process.argv[2];
function csv(file){const rows=fs.readFileSync(path.join(run,file),'utf8').trim().split(/\r?\n/).map(l=>l.split(','));const head=rows.shift();return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]])));}
const bom=csv('BOM.csv'),measured=csv('measured-geometry.csv'),map=new Map(measured.map(m=>[m.Part,m]));
let discrepancies=[];
for(const p of bom){let m=map.get(p.Part);if(!m){discrepancies.push(`${p.Part}: no measured geometry`);continue;}for(const k of ['Width_mm','Height_mm','Depth_mm']){let expected=+p[k];if(p.Shape.startsWith('half_')&&k==='Height_mm')expected/=2;if(p.Part.startsWith('Rail_bridge_')&&k==='Depth_mm'&&fs.existsSync(path.join(run,'hardware-detail-checks.txt')))expected=5-(Math.sqrt(27*27-6*6)-26);if(Math.abs(+m[k]-expected)>.15)discrepancies.push(`${p.Part}: ${k} expected ${expected}; measured ${m[k]}`);}if(+m.Solids!==1||m.RebuildOK!=='True')discrepancies.push(`${p.Part}: solids=${m.Solids}, rebuild=${m.RebuildOK}`);}
const sketches=fs.readFileSync(path.join(run,'verified-sketches.txt'),'utf8').trim().split(/\r?\n/);
const bad=sketches.filter(l=>!l.endsWith('after=3'));
let text=`# Validation record\n\n- ${bom.length} model components and ${measured.length-bom.length} host-reference parts measured.\n- ${measured.filter(m=>m.RebuildOK==='True'&&+m.Solids===1).length} parts rebuilt with one solid body each.\n- ${sketches.length} sketches inspected; ${bad.length} not fully constrained after anchoring.\n- ${discrepancies.length} nominal-envelope/body-count discrepancies at 0.15 mm tolerance.\n\nThe raw verifier log ends with an attempted read of a transient SolidWorks '~$' lock file. This is not a CAD part. All ${measured.length} real part files had already completed reopening, rebuilding, saving and measurement. The generator's file filter now excludes lock files; no real part was skipped.\n\nFinal assembly placement and collision results are in final-interferences.txt. The independent exploded assembly prevents its component offsets from propagating to installed configurations. Static model checks do not establish working strip transport, structural capacity, hygiene performance or clinical accuracy.\n`;
if(discrepancies.length)text+='\n## Envelope discrepancies\n\n'+discrepancies.map(d=>'- '+d).join('\n')+'\n';
if(bad.length)text+='\n## Sketch exceptions\n\n'+bad.join('\n');
if(fs.existsSync(path.join(run,'final-interferences.txt'))){const lines=fs.readFileSync(path.join(run,'final-interferences.txt'),'utf8').trim().split(/\r?\n/).filter(l=>l.includes('INTERFERENCE_COUNT='));text+='\n## Final static assembly check\n\n'+lines.map(l=>'- '+l).join('\n')+'\n\nOnly static solid interference is assessed. This does not prove clearance throughout motion, mount load capacity or a functioning feed/eject mechanism.\n';}
fs.writeFileSync(path.join(run,'VALIDATION.md'),text);
console.log(JSON.stringify({parts:measured.length,sketches:sketches.length,sketchExceptions:bad,geometryDiscrepancies:discrepancies},null,2));
