using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using SolidWorks.Interop.sldworks;
class FinalAudit{
 [STAThread]static void Main(string[] args){string run=args[0];SldWorks sw=null;try{sw=(SldWorks)Marshal.GetActiveObject("SldWorks.Application");sw.CommandInProgress=true;int e=0,w=0;var d=(ModelDoc2)sw.OpenDoc6(Path.Combine(run,"parts","Hook_protective_pad.SLDPRT"),1,1,"",ref e,ref w);sw.ActivateDoc3(d.GetTitle(),false,0,ref e);var eq=(EquationMgr)d.GetEquationMgr();for(int i=0;i<eq.GetCount();i++)if(eq.get_Equation(i).StartsWith("\"Profile_Depth\""))eq.set_Equation(i,"\"Profile_Depth\" = 53mm");if(!d.EditRebuild3())throw new Exception("Pad rebuild failed");d.Save3(1,ref e,ref w);var body=(Body2)((object[])((PartDoc)d).GetBodies2(0,false))[0];var b=(double[])body.GetBodyBox();var mass=(double[])body.GetMassProperties(1);var measured=File.ReadAllLines(Path.Combine(run,"measured-geometry.csv"));for(int i=1;i<measured.Length;i++)if(measured[i].StartsWith("Hook_protective_pad,"))measured[i]="Hook_protective_pad,"+((b[3]-b[0])*1000)+","+((b[4]-b[1])*1000)+","+((b[5]-b[2])*1000)+","+(mass[3]*1e9)+",1,True";File.WriteAllLines(Path.Combine(run,"measured-geometry.csv"),measured);sw.CloseDoc(d.GetTitle());
  var bom=File.ReadAllLines(Path.Combine(run,"BOM.csv"));for(int i=1;i<bom.Length;i++)if(bom[i].StartsWith("Hook_protective_pad,")){var f=bom[i].Split(',');f[5]="53";bom[i]=string.Join(",",f);}File.WriteAllLines(Path.Combine(run,"BOM.csv"),bom);
  var model=(ModelDoc2)sw.OpenDoc6(Path.Combine(run,"Luma_Retrofit.SLDASM"),2,1,"",ref e,ref w);sw.ActivateDoc3(model.GetTitle(),false,0,ref e);var ass=(AssemblyDoc)model;var logs=new List<string>();var counts=new List<string>();
  foreach(string cfg in ((string[])model.GetConfigurationNames()).Where(c=>c.EndsWith("_DC")||c.EndsWith("_Battery"))){model.ShowConfiguration2(cfg);model.EditRebuild3();var mgr=ass.InterferenceDetectionManager;mgr.TreatCoincidenceAsInterference=false;var found=(object[])mgr.GetInterferences();logs.Add(cfg+" INTERFERENCE_COUNT="+(found==null?0:found.Length));if(found!=null)foreach(Interference f in found)logs.Add(cfg+" "+string.Join(" / ",((object[])f.Components).Cast<Component2>().Select(c=>c.Name2))+" mm3="+(f.Volume*1e9));counts.Add(cfg+" active="+((object[])ass.GetComponents(false)).Cast<Component2>().Count(c=>c.GetSuppression()!=0));Console.WriteLine(logs.Last());}
  model.ShowConfiguration2("Hook_DC");model.ShowNamedView2("*Isometric",7);model.ViewZoomtofit2();model.SaveBMP(Path.Combine(run,"views","Hook.bmp"),1400,1100);model.ShowConfiguration2("Partition_DC");model.ShowNamedView2("*Isometric",7);model.ViewZoomtofit2();model.FeatureManager.EnableFeatureTree=true;model.Save3(1,ref e,ref w);File.WriteAllLines(Path.Combine(run,"final-interferences.txt"),logs);File.WriteAllLines(Path.Combine(run,"configuration-checks.txt"),counts);
 }catch(Exception e){Console.WriteLine(e);System.Environment.ExitCode=1;}finally{if(sw!=null){sw.CommandInProgress=false;sw.DocumentVisible(true,1);}}}
}
