using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using SolidWorks.Interop.sldworks;
class HardwareDetails{
 [STAThread]static void Main(string[] args){string run=args[0];SldWorks sw=null;try{sw=(SldWorks)Marshal.GetActiveObject("SldWorks.Application");sw.CommandInProgress=true;int er=0,wa=0;var open=(ModelDoc2)sw.GetOpenDocumentByName(Path.Combine(run,"Luma_Retrofit.SLDASM"));if(open!=null){open.Save3(1,ref er,ref wa);sw.CloseDoc(open.GetTitle());}var logs=new List<string>();
  var measured=File.ReadAllLines(Path.Combine(run,"measured-geometry.csv")).ToList();
  foreach(string name in new[]{"09_Rear_standoff_L","10_Rear_standoff_R","Partition_moving_jaw_0","Partition_moving_jaw_1","Rail_bridge_0","Rail_bridge_1"}){
   var d=(ModelDoc2)sw.OpenDoc6(Path.Combine(run,"parts",name+".SLDPRT"),1,1,"",ref er,ref wa);sw.ActivateDoc3(d.GetTitle(),false,0,ref er);bool rail=name.StartsWith("Rail_");d.ClearSelection2(true);d.Extension.SelectByID2(rail?"Top Plane":"Front Plane","PLANE",0,0,0,false,0,null,0);d.SketchManager.InsertSketch(true);d.SketchManager.AddToDB=true;var sk=(Sketch)d.GetActiveSketch2();
   var mu=(MathUtility)sw.GetMathUtility();double[][] holes=rail?new[]{new[]{.006,0,-.026,.027}}:name.Contains("standoff")?new[]{new[]{.006,.006,0,.00225},new[]{.006,.238,0,.00225}}:new[]{new[]{.020,.017,0,.00405}};
   foreach(var h in holes){var pt=(MathPoint)mu.CreatePoint(new[]{h[0],h[1],h[2]});var p=(double[])((MathPoint)pt.MultiplyTransform(sk.ModelToSketchTransform)).ArrayData;d.SketchManager.CreateCircleByRadius(p[0],p[1],0,h[3]);}
   d.SketchManager.AddToDB=false;d.ClearSelection2(true);((SketchPoint)((object[])sk.GetSketchPoints2())[0]).Select4(false,null);d.SketchAddConstraints("sgFIXED");d.ClearSelection2(true);d.SketchManager.FullyDefineSketch(true,true,518,true,0,null,0,null,0,0);int status=sk.GetConstrainedStatus();d.SketchManager.InsertSketch(true);((Feature)sk).Select2(false,0);
   var cut=d.FeatureManager.FeatureCut3(false,false,false,1,1,.05,.05,false,false,false,false,0,0,false,false,false,false,false,true,true,false,false,false,0,0,false);if(cut==null)throw new Exception("Cut failed "+name);cut.Name=rail?"Saddle_contact_relief":"Fastener_clearance";bool rebuilt=d.EditRebuild3();int e=0,w=0;bool saved=d.Save3(1,ref e,ref w);if(!rebuilt||!saved||status!=3)throw new Exception("Detail check failed "+name+" sketch="+status);
   var body=(Body2)((object[])((PartDoc)d).GetBodies2(0,false))[0];var b=(double[])body.GetBodyBox();var mass=(double[])body.GetMassProperties(1);string line=name+","+((b[3]-b[0])*1000)+","+((b[4]-b[1])*1000)+","+((b[5]-b[2])*1000)+","+(mass[3]*1e9)+",1,True";int idx=measured.FindIndex(l=>l.StartsWith(name+","));measured[idx]=line;
   File.AppendAllText(Path.Combine(run,"verified-sketches.txt"),name+" / "+cut.Name+" before=3 after="+status+System.Environment.NewLine);logs.Add(name+" cut="+cut.Name+" rebuild="+rebuilt+" saveErrors="+e);Console.WriteLine(logs.Last());sw.CloseDoc(d.GetTitle());
  }
  File.WriteAllLines(Path.Combine(run,"measured-geometry.csv"),measured);File.WriteAllLines(Path.Combine(run,"hardware-detail-checks.txt"),logs);
  var model=(ModelDoc2)sw.OpenDoc6(Path.Combine(run,"Luma_Retrofit.SLDASM"),2,1,"",ref er,ref wa);sw.ActivateDoc3(model.GetTitle(),false,0,ref er);model.ShowConfiguration2("Hook_DC");var a=(AssemblyDoc)model;foreach(Component2 c in (object[])a.GetComponents(false))if(c.Name2.StartsWith("Hook_front_drop")){model.ClearSelection2(true);c.Select4(false,null,false);a.UnfixComponent();c.Transform2=(MathTransform)((MathUtility)sw.GetMathUtility()).CreateTransform(new[]{1.0,0,0,0,1,0,0,0,1,-.035,.260,-.020,1,0,0,0});a.FixComponent();}
  model.ClearSelection2(true);model.EditRebuild3();model.ShowConfiguration2("Partition_DC");model.Save3(1,ref er,ref wa);
  var bom=File.ReadAllLines(Path.Combine(run,"BOM.csv"));for(int i=1;i<bom.Length;i++)if(bom[i].StartsWith("Hook_front_drop,")){var fields=bom[i].Split(',');fields[9]="-20";bom[i]=string.Join(",",fields);}File.WriteAllLines(Path.Combine(run,"BOM.csv"),bom);
 }catch(Exception e){Console.WriteLine(e);System.Environment.ExitCode=1;}finally{if(sw!=null)sw.CommandInProgress=false;}}
}
