using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using SolidWorks.Interop.sldworks;
class FinalizeCAD{
 static SldWorks sw;
 [STAThread]static void Main(string[] args){string run=args[0];try{sw=(SldWorks)Marshal.GetActiveObject("SldWorks.Application");sw.CommandInProgress=true;int er=0,wa=0;var d=(ModelDoc2)sw.OpenDoc6(Path.Combine(run,"Luma_Retrofit.SLDASM"),2,1,"",ref er,ref wa);sw.ActivateDoc3(d.GetTitle(),false,0,ref er);var a=(AssemblyDoc)d;d.ShowConfiguration2("Partition_DC");d.FeatureManager.EnableFeatureTree=false;
  var rows=File.ReadAllLines(Path.Combine(run,"BOM.csv")).Skip(1).Select(l=>l.Split(',')).ToDictionary(r=>r[0]);rows["20_Sealed_strip_cassette"][8]="87";rows["21_Cassette_sealed_lid"][8]="89";
  string header=File.ReadLines(Path.Combine(run,"BOM.csv")).First();File.WriteAllLines(Path.Combine(run,"BOM.csv"),new[]{header}.Concat(rows.Values.Select(r=>string.Join(",",r))));
  foreach(Component2 c in (object[])a.GetComponents(false)){string k=Path.GetFileNameWithoutExtension(c.GetPathName());if(!rows.ContainsKey(k))continue;var r=rows[k];if(r[1]=="Core"){c.SetSuppression2(2);d.ClearSelection2(true);c.Select4(false,null,false);a.UnfixComponent();double x=double.Parse(r[7])/1000,y=double.Parse(r[8])/1000,z=double.Parse(r[9])/1000;c.Transform2=(MathTransform)((MathUtility)sw.GetMathUtility()).CreateTransform(new[]{1.0,0,0,0,1,0,0,0,1,x,y,z,1,0,0,0});a.FixComponent();}
   double[] rgb=r[10].Contains("steel")?new[]{.65,.70,.74}:r[10].Contains("Black")||r[10]=="EPDM"?new[]{.08,.12,.14}:r[10].Contains("PCB")?new[]{.15,.60,.40}:k.Contains("waste")||k.Contains("Waste")?new[]{.95,.55,.16}:k.Contains("frame")||k.Contains("bezel")||k.Contains("drawer")?new[]{.03,.48,.48}:new[]{.86,.92,.94};c.SetMaterialPropertyValues2(new[]{rgb[0],rgb[1],rgb[2],1.0,1.0,.15,.05,0,0},2,null);
  }
  d.ClearSelection2(true);d.DeleteConfiguration2("Exploded_Core");d.EditRebuild3();d.Save3(1,ref er,ref wa);Console.WriteLine("Restored base positions");
  // Independent assembly preserves the operational configurations' placements.
  var exp=(ModelDoc2)sw.NewDocument(@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\Assembly.ASMDOT",0,0,0);var ea=(AssemblyDoc)exp;var core=rows.Values.Where(r=>r[1]=="Core").ToArray();var files=core.Select(r=>Path.Combine(run,"parts",r[0]+".SLDPRT")).ToArray();var transforms=new List<double>();
  for(int i=0;i<core.Length;i++){var r=core[i];double x=(double.Parse(r[7])+(i%5-2)*250)/1000,y=(double.Parse(r[8])+(i/5)*160)/1000,z=(double.Parse(r[9])+(i%5)*130)/1000;transforms.AddRange(new[]{1.0,0,0,0,1,0,0,0,1,x,y,z,1,0,0,0});}
  var inserted=(object[])ea.AddComponents3(files,transforms.ToArray(),Enumerable.Repeat("",files.Length).ToArray());if(inserted==null||inserted.Length!=files.Length)throw new Exception("Exploded batch insert failed");
  exp.EditRebuild3();exp.ShowNamedView2("*Isometric",7);exp.ViewZoomtofit2();exp.Extension.SaveAs(Path.Combine(run,"Luma_Exploded.SLDASM"),0,1,null,ref er,ref wa);exp.SaveBMP(Path.Combine(run,"views","Exploded.bmp"),1600,1200);sw.CloseDoc(exp.GetTitle());sw.ActivateDoc3(d.GetTitle(),false,0,ref er);
  foreach(string cfg in new[]{"Partition_DC","Rail_DC","Hook_DC","Pedestal_DC","Smooth_DC","Magnetic_DC","Installed_Partition","Installed_Rail","Installed_Pedestal","Installed_Smooth","Service_Open"}){d.ShowConfiguration2(cfg);d.EditRebuild3();d.ShowNamedView2("*Isometric",7);d.ViewZoomtofit2();string name=cfg.EndsWith("_DC")?cfg.Substring(0,cfg.Length-3):cfg;d.SaveBMP(Path.Combine(run,"views",name+".bmp"),1400,1100);Console.WriteLine("View "+cfg);}
  d.ShowConfiguration2("Partition_DC");d.FeatureManager.EnableFeatureTree=true;d.EditRebuild3();d.ShowNamedView2("*Isometric",7);d.ViewZoomtofit2();d.Save3(1,ref er,ref wa);
  var checks=new List<string>();foreach(string cfg in new[]{"Partition_DC","Rail_DC","Hook_DC","Pedestal_DC","Smooth_DC","Magnetic_DC"}){d.ShowConfiguration2(cfg);d.EditRebuild3();var mgr=a.InterferenceDetectionManager;mgr.TreatCoincidenceAsInterference=false;var found=(object[])mgr.GetInterferences();checks.Add(cfg+" INTERFERENCE_COUNT="+(found==null?0:found.Length));if(found!=null)foreach(Interference f in found)checks.Add(cfg+" "+string.Join(" / ",((object[])f.Components).Cast<Component2>().Select(c=>c.Name2))+" mm3="+(f.Volume*1e9));}
  File.WriteAllLines(Path.Combine(run,"final-interferences.txt"),checks);d.ShowConfiguration2("Partition_DC");d.Save3(1,ref er,ref wa);
  string drawPath=Path.Combine(run,"Luma_GA.SLDDRW");if(File.Exists(drawPath)){var dr=(ModelDoc2)sw.OpenDoc6(drawPath,3,1,"",ref er,ref wa);if(dr!=null){dr.ForceRebuild3(false);dr.Save3(1,ref er,ref wa);sw.CloseDoc(dr.GetTitle());}}
  sw.ActivateDoc3(d.GetTitle(),false,0,ref er);d.ViewZoomtofit2();Console.WriteLine("Finalized");
 }catch(Exception e){Console.WriteLine(e);System.Environment.ExitCode=1;}finally{if(sw!=null){sw.CommandInProgress=false;sw.DocumentVisible(true,1);}}}
}
